<a href="https://colab.research.google.com/github/PAVAN-DEVMURARI/ML-Practicals/blob/main/feature_construction_and_feature_splitting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np

In [5]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression

import seaborn as sns

In [6]:
df = pd.read_csv ('/content/train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [7]:
df.sample(10)

      Age  Pclass  SibSp  Parch  Survived
375   NaN       1      1      0         1
383  35.0       1      1      0         1
565  24.0       3      2      0         0
106  21.0       3      0      0         1
272  41.0       2      0      1         1
486  35.0       1      1      0         1
79   30.0       3      0      0         1
255  29.0       3      0      2         1
198   NaN       3      0      0         1
442  25.0       3      1      0         0

In [8]:
df.dropna(inplace=True)

In [9]:
df.shape

(714, 5)

In [10]:
df.sample(10)

      Age  Pclass  SibSp  Parch  Survived
349  42.0       3      0      0         0
131  20.0       3      0      0         0
381   1.0       3      0      2         1
75   25.0       3      0      0         0
609  40.0       1      0      0         1
491  21.0       3      0      0         0
788   1.0       3      1      2         1
752  33.0       3      0      0         0
269  35.0       1      0      0         1
796  49.0       1      0      0         1

In [11]:
df_2 = pd.read_csv ('/content/train.csv')[['Age','Pclass','SibSp','Parch','Survived']]

In [12]:
df_2.shape

(891, 5)

In [13]:
X = df.iloc[:,0:4]
y = df.iloc[:,-1]

In [14]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=200))

np.float64(0.7045833333333333)

**Apply Feature Construction**

In [15]:
X['Family_size'] = X['SibSp'] + X['Parch'] +1

In [16]:
X.sample(10)

      Age  Pclass  SibSp  Parch  Family_size
520  30.0       1      0      0            1
219  30.0       2      0      0            1
460  48.0       1      0      0            1
348   3.0       3      1      1            3
750   4.0       2      1      1            3
83   28.0       1      0      0            1
327  36.0       2      0      0            1
275  63.0       1      1      0            2
455  29.0       3      0      0            1
647  56.0       1      0      0            1

In [17]:
def myfunc (num):
  if num == 1:
    return 0
  elif num > 1 and num <= 4:
    return 1
  else:
    return 2

In [18]:
myfunc(2)

1

In [19]:
X['Family_type'] = X['Family_size'].apply(myfunc)

In [20]:
X.sample(10)

      Age  Pclass  SibSp  Parch  Family_size  Family_type
694  60.0       1      0      0            1            0
51   21.0       3      0      0            1            0
821  27.0       3      0      0            1            0
282  16.0       3      0      0            1            0
771  48.0       3      0      0            1            0
79   30.0       3      0      0            1            0
37   21.0       3      0      0            1            0
782  29.0       1      0      0            1            0
251  29.0       3      1      1            3            1
195  58.0       1      0      0            1            0

In [21]:
X.drop(columns = ['SibSp','Parch','Family_size'],inplace=True)

In [22]:
X.sample(10)

      Age  Pclass  Family_type
135  23.0       2            0
853  16.0       1            1
690  31.0       1            1
528  39.0       3            0
835  39.0       1            1
147   9.0       3            2
402  21.0       3            1
93   26.0       3            1
365  30.0       3            0
446  13.0       2            1

In [23]:
np.mean(cross_val_score(LogisticRegression(),X,y,scoring='accuracy',cv=210))

np.float64(0.7123015873015872)

# **Feature Splitting**

In [24]:
df_2 = pd.read_csv('/content/train.csv')

In [25]:
df_2.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
179,180,0,3,"Leonard, Mr. Lionel",male,36.0,0,0,LINE,0.0000,NaN,S
501,502,0,3,"Canavan, Miss. Mary",female,21.0,0,0,364846,7.7500,NaN,Q
289,290,1,3,"Connolly, Miss. Kate",female,22.0,0,0,370373,7.7500,NaN,Q
477,478,0,3,"Braund, Mr. Lewis Richard",male,29.0,1,0,3460,7.0458,NaN,S
446,447,1,2,"Mellinger, Miss. Madeleine Violet",female,13.0,0,1,250644,19.5000,NaN,S
655,656,0,2,"Hickman, Mr. Leonard Mark",male,24.0,2,0,S.O.C. 14879,73.5000,NaN,S
290,291,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.0,0,0,19877,78.8500,NaN,S
181,182,0,2,"Pernot, Mr. Rene",male,NaN,0,0,SC/PARIS 2131,15.0500,NaN,C
135,136,0,2,"Richard, Mr. Emile",male,23.0,0,0,SC/PARIS 2133,15.0458,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.0,1,2,C.A. 34651,27.7500,NaN,S

In [27]:
df_2['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [30]:
df_2['Title'] = df_2['Title'] = df_2['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

In [32]:
df_2['Name'].str.split(', ', expand=True)[1].str.split('.', expand=True)[0]

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     Rev
887    Miss
888    Miss
889      Mr
890      Mr
Name: 0, Length: 891, dtype: object

In [35]:
df_2[['Title','Name']]

    Title                                               Name
0      Mr                            Braund, Mr. Owen Harris
1     Mrs  Cumings, Mrs. John Bradley (Florence Briggs Th...
2    Miss                             Heikkinen, Miss. Laina
3     Mrs       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4      Mr                           Allen, Mr. William Henry
..    ...                                                ...
886   Rev                              Montvila, Rev. Juozas
887  Miss                       Graham, Miss. Margaret Edith
888  Miss           Johnston, Miss. Catherine Helen "Carrie"
889    Mr                              Behr, Mr. Karl Howell
890    Mr                                Dooley, Mr. Patrick

[891 rows x 2 columns]

In [38]:
(df_2.groupby('Title')['Survived'].mean()).sort_values(ascending=False)

Title
Lady            1.000000
Ms              1.000000
Sir             1.000000
Mme             1.000000
the Countess    1.000000
Mlle            1.000000
Mrs             0.792000
Miss            0.697802
Master          0.575000
Major           0.500000
Col             0.500000
Dr              0.428571
Mr              0.156673
Capt            0.000000
Jonkheer        0.000000
Don             0.000000
Rev             0.000000
Name: Survived, dtype: float64

In [41]:

df_2['Is_Married'] = 0
df_2['Is_Married'].loc[df_2['Title'] == 'Mrs'] = 1

/tmp/ipython-input-41-2731340941.py:2: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df_2['Is_Married'].loc[df_2['Title'] == 'Mrs'] = 1
/tmp/ipython-input-41-2731340941.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2['Is_Married'].loc[df_2['Title'] == 'Mrs'] = 1

In [43]:
df_2['Is_Married']

0      0
1      1
2      0
3      1
4      0
      ..
886    0
887    0
888    0
889    0
890    0
Name: Is_Married, Length: 891, dtype: int64